# enable zmk studio for realtime keymap updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Mouse Navigation Driver
CONFIG_ZMK_MOUSE=y

# Dual Battery Proxy Options
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Bluetooth battery update fix
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
